## Q1

In [1]:
#Program that calculates and prints the value according to the given formula:
# Q = Square root of [(2 * C * D)/H] where C = 50 and H = 30

import math

num = input("Enter the value of D: ").split(',')

C = 50
H = 30

ans = []
for n in num:
    Q = round(math.sqrt(2 *C* int(n) / H))
    ans.append(str(Q))


out_val = ",".join(ans).replace("'"," ")
print("\n",out_val)

Enter the value of D: 100,150,180

 18,22,24


## Q2

In [2]:
# Program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The
# element value in the i-th row and j-th column of the array should be i*j.

#Note: i=0,1.., X-1; j=0,1,¡Y-1.
import numpy as np

X = int(input("Enter the value of X: "))
Y = int(input("Enter the value of Y: "))
arr = np.zeros((X,Y),dtype=int)
for i in range(X):
    for j in range(Y):
        arr[i][j]=i*j

print("\nThe resulting array is: \n",arr)

Enter the value of X: 3
Enter the value of Y: 5

The resulting array is: 
 [[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


## Q3

In [3]:
# Program that accepts a comma separated sequence of words as input and prints the
# words in a comma-separated sequence after sorting them alphabetically

word_str = str(input("\nEnter the comma-separated sequence of words: "))
word_list = word_str.split(",")


word_list.sort()
print(",".join(word_list))



Enter the comma-separated sequence of words: without,hello,bag,world
bag,hello,without,world


## Q4

In [4]:
#Program that accepts a sequence of whitespace separated words as input and prints
# the words after removing all duplicate words and sorting them alphanumerically

word_str = str(input("\nEnter the space-separated sequence of words: "))
word_list = word_str.split(" ")


word_uniq = list(set(word_list))
word_uniq.sort()

print("\n"," ".join(word_uniq))


Enter the space-separated sequence of words: hello world and practice makes perfect and hello world again

 again and hello makes perfect practice world


## Q5

In [5]:
# Program that accepts a sentence and calculate the number of letters and digits.

word_str = str(input("\nEnter the space-separated sequence of words: "))

l = 0
n = 0
for i in list(word_str):
    if(i.isdigit()==True):
        n = n +1 
    elif(i.isalpha()==True):
        l= l +1
        
print("LETTERS",l)
print("DIGITS",n)


Enter the space-separated sequence of words: hello world! 123
LETTERS 10
DIGITS 3


## Q6

In [6]:
#A website requires the users to input username and password to register. Write a program to
#check the validity of password input by users

import re

pwd_list = input("Enter the passwords: ").split(",")

acc_pwd = []

for i in pwd_list:
    
    if (len(i) < 6 or len(i) > 12):
        continue

    elif not re.search("([a-z])+", i):
        continue

    elif not re.search("([A-Z])+", i):
        continue

    elif not re.search("([0-9])+", i):
        continue

    elif not re.search("([!@$%^&])+", i):
        continue

    else:
        acc_pwd.append(i)

print((" ").join(acc_pwd))

Enter the passwords: ABd1234@1,a F1#,2w3E*,2We3345
ABd1234@1
